apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse-rias
    type: grafana-clickhouse-datasource
    access: proxy
    url: clickhouse:9000
    isDefault: true
    jsonData:
      protocol: native
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: rias
      tlsSkipVerify: true
    secureJsonData:
      password: rias
    editable: true
